### ISSUE TITLE
COOK-4336: remove simple "apache_module" recipes from apache2 cookbook except as needed for default recipe 

### ISSUE THREAD

**Issue by svanzoest** [sous-chefs/apache2#214]
https://tickets.opscode.com/browse/COOK-4336 by Joshua Timberman @jtimberman 

Except as included by the "default" recipe, all the "mod_" recipes in the apache2 cookbook should be removed if the only thing they do is "apache_module 'mod_name'."

Where applicable for the "default_modules" attribute, the corresponding apache_module should be used instead, in the default recipe (see COOK-4335, #228 ).

**Comment by damacus** [comment]
Closing this down and tracking as part of the rewrite 6.0 milestone.
