### ISSUE TITLE
Add ability to set ip address for web app conf

### ISSUE THREAD

**Issue by dmyers** [sous-chefs/apache2#240]
It would be nice to be able to set the ip address when creating virtual hosts using the web_app() definition and fallback to an attribute similar to the server_port() definition/attribute. Currently it is set to just *.

https://github.com/onehealth-cookbooks/apache2/blob/master/templates/default/web_app.conf.erb#L1

**Comment by alexandrezia** [comment]
Just pass the variables as parameters of the web_app definition.
web_app is not the final template resource, it is a definition that will call the template resource

```
web_app 'working' do
  template 'working.conf.erb'
  server_name node['hostname']
  server_aliases [node['fqdn']]
  docroot node['apache']['docroot_dir']
  your_variable('value')
  your_variable2('value2')
end
```

Then in the template reference them as:

```
<% @params[:your_variable] %>
...
<% @params[:your_variable2] %>
```

That works for me.
