### ISSUE TITLE
Remove all default templates to simplify cookbook

### ISSUE THREAD

**Issue by svanzoest** [sous-chefs/apache2#336]
We are getting a lot of requests for updates on the default `web_app` template which is not maintainable in the long run. As it is expected that people will wrap this cookbook for their own usage a template can be provided by the wrapper cookbook. We need to make it more clear that most flexible way to handle this is for the user of the cookbook to own the templates. It is hard to have them to be fully attribute driven as there is structure in apache configuration files.

We can still ship the default template files part of our integration tests, so we can point at them if users are looking for a basic template to build on top that.

**Comment by Maks3w** [comment]
I prefer to have a quick setup with some defaults and customize when the needs grown.

May highlight the way of use custom templates is enough.

**Comment by svanzoest** [comment]
@Maks3w the default would be not to have any vhosts, similar to a fresh httpd package install.

**Comment by nkadel-skyhook** [comment]
> We need to make it more clear that most flexible way to handle this is for the user of the cookbook to own the templates.

Than that default is pretty useless and forces every admin to hand build their own wrapper cookbooks. I'd strongly encourage a very simple, default disabled vhost as a basic working configuration for admins to follow as an example.

**Comment by svanzoest** [comment]
You do not need to write a wrapper tobuse your own templates. You can
already pass those in via the definitions.

**Comment by damacus** [comment]
Closing this down as we're looking at trying to drop support for 2.2.
