### ISSUE TITLE
Forbidden issue with custom htaccess filename

### ISSUE THREAD

**Issue by bhupesh** [sous-chefs/apache2#400]
My custom htaccess filename is .iaccess. When I visit url starting with /via, it will forbid access to the url. 
Please escape `access_file_name_prefix` at https://github.com/svanzoest-cookbooks/apache2/blob/master/templates/default/apache2.conf.erb#L96

**Comment by svanzoest** [comment]
@bhupesh the prefix is already anchored via `^` to the beginning of the file. Can you provide an example test case that fails?

**Comment by bhupesh** [comment]
@svanzoest if the apache configuration has the constom `.htaccess` filename, which in my case had `.iaccess`. `.htaccess` filename has `.` property escaped by using `\.`, while if the filename is not `.htaccess`, it directly places the first 3 characters of the file. Therefore, it results in `<Files ~ "^(.ia|\.ht)">`, `.` will match any character and it will forbid access to all the urls that has `ia` as their second and third character.
I will try to find time to implement a test case.

**Comment by damacus** [comment]
Hi there! 

can you see if this is still a case on the current version of master. 

Closing as this is a very old ticket
