### ISSUE TITLE
convert definitions to custom resources

### ISSUE THREAD

**Issue by svanzoest** [sous-chefs/apache2#414]
Since the release of chef 12.5 we have access to [custom resources](https://docs.chef.io/custom_resources.html) that seem like a more suited method versus using LWRPs for this cookbook #178

**Comment by stissot** [comment]
Unlike Definitions, Custom resources support features like guards (`only_if`, `not_if`)

**Comment by damacus** [comment]
yeah, this is done now. 
They're not complete. But there are now no definitions left on master.
