### ISSUE TITLE
apache_conf doesn't seem to disable configs

### ISSUE THREAD

**Issue by adiamas** [sous-chefs/apache2#435]
I'm using apache_conf to disable configurations installed by apache by default (other-vhosts-access-log specifically) and the following doesn't appear to work:

```
apache_conf 'other-vhosts-access-log' do
   enable false
end

```

however using apache_config does work as expected.  It appears that the definition for apache_conf:

```
  if params[:enable]
    apache_config params[:name] do
      enable true
    end
  end
```

Indicates that if we have a configuration file previously enabled, and it is set disabled, apache_config is never actually called since params[:enable] is 'false'.  Am I missing something?

**Comment by drpebcak** [comment]
That is actually correct. You could try using `apache_config` directly though, instead of going through `apache_conf`.

`apache_config` will run `a2disconf` if enable != true

**Comment by adiamas** [comment]
I've opted to use apache_config, and that is working as expected. The current logic in apache_conf doesn't match the documentation. There's no way for an "enable false" to be executed. Either the code or the documentation should be update to reflect this for sure.

**Comment by drpebcak** [comment]
Yeah.. the documentation does say that should work. We should probably fix this so it does the same thing `apache_config` does.

**Comment by damacus** [comment]
Hi there! 

can you see if this is still a case on the current version of master. 

Closing as this is a very old ticket
