### ISSUE TITLE
rename repo to apache2-cookbook

### ISSUE THREAD

**Issue by tas50** [sous-chefs/apache2#452]
To match our other cookbook repos this one should get renamed

**Comment by svanzoest** [comment]
I am all for consistency, but I have been holding off based on [#chef-brigade](http://chefcommunity.slackarchive.io/chef-brigade/-/1478634100.001171/1478731420.001287/1478636890001201/) discussion with @josephholsten

**Comment by josephholsten** [comment]
won't fix, we changed our minds. This is correct according to https://github.com/sous-chefs/meta/blob/master/transfering-a-cookbook.md
