### ISSUE TITLE
service[apache2]

### ISSUE THREAD

**Issue by marzzz21** [sous-chefs/apache2#457]
### Cookbook version
'~> 3.2.2'

### Chef-client version
12.15.19

### Platform Details
CentOS 7.2

### Scenario:
Installing a base working apache/http server.

### Steps to Reproduce:
I just included the recipe apache2::default

### Expected Result:
To have apache successfully installed.

### Actual Result:
https://gist.github.com/marzzz21/7a6e1c838a1d7b7a5f36b2ae2b0c2351

**Comment by svanzoest** [comment]
```
================================================================================
Error executing action `enable` on resource 'service[apache2]'
================================================================================
           
Errno::ENOENT
-------------
No such file or directory - /usr/sbin/httpd.worker
 ```          

How did `apache.binary` get set to `/usr/sbin/httpd.worker`?

**Comment by marzzz21** [comment]
Checked the attributes, and it appears there was an attribute overriding the path to /usr/bin/httpd.worker. The cookbook worked for CentOS6.8 though. Anyway, this was my mistake, I apologize for bringing it up here.
