### ISSUE TITLE
apache_module should not overwrite load files

### ISSUE THREAD

**Issue by 375gnu** [sous-chefs/apache2#458]
### Cookbook version
3.2.2

### Chef-client version
12.16.42

### Platform Details
Ubuntu 14.04

### Scenario:
I want to install and enable mod_security2.

### Steps to Reproduce:
package %w[libapache2-mod-security2 modsecurity-crs]
apache_module 'security2'

### Expected Result:
mod_security2.load provided with package to be used.

### Actual Result:
mod_security2.load is overwritten with incorrect version:
```
         * file[/etc/apache2/mods-available/security2.load] action create
           - update content in file /etc/apache2/mods-available/security2.load from 8a3b11 to 078ef6
           --- /etc/apache2/mods-available/security2.load	2014-01-16 07:53:00.000000000 +0000
           +++ /etc/apache2/mods-available/.chef-security220161208-13005-tf2t91.load	2016-12-08 16:22:17.995719528 +0000
           @@ -1,4 +1,2 @@
           -# Depends: unique_id
           -LoadFile libxml2.so.2
            LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so
```

So 
```
  file "#{node['apache']['dir']}/mods-available/#{params[:name]}.load" do
    content "LoadModule #{params[:identifier]} #{params[:module_path]}\n"
    mode '0644'
  end
```
should check for *.load file presence.

**Comment by damacus** [comment]
This seems like a bug! 

If you want to take up fixing this, please drop in a PR. If you need help where to start, the #sous-chefs channel on the chef community slack is a great please to get started.

Thanks,
Dan

**Comment by josephholsten** [comment]
@damacus says that he no-longer considers this a bug. That probably means some documentation would be the best solution.

**Comment by josephholsten** [comment]
it would be awesome to have full-on documentation pages instead of a readme the size of war & peace. macos cookbook has a good example.

**Comment by damacus** [comment]
Closing this as it's been open for a while now without comment. If you have any suggested way of moving this issue forward please drop us a line!
