### ISSUE TITLE
When only listen_ports are defined, the merging in the helper library fails

### ISSUE THREAD

**Issue by daften** [sous-chefs/apache2#459]
### Cookbook version
3.2.2

### Chef-client version
irrelevant

### Platform Details
Ubuntu 14.04 but irrelevant

### Scenario:
Still use the cookbook with the old listen_ports (legacy that was in place)

### Steps to Reproduce:
Run with only listen_ports defined and not listen_addresses

### Expected Result:
It should merge the old attributes and convert to the new scheme

### Actual Result:
It throws an error because I don't have listen_addresses. The uniq on line 37 in listen.rb fails node['apache']['listen_addresses'].uniq since node['apache']['listen_addresses'] is a nil class.

**Comment by laradji** [comment]
+1

**Comment by hrak** [comment]
Appears to be fixed in #422 but that change has not made it into a new release yet. @svanzoest could you please cut a new release? (master includes some neat changes & fixes)

**Comment by svanzoest** [comment]
Released https://github.com/sous-chefs/apache2/releases/tag/v3.3.0
