### ISSUE TITLE
master has important changes that haven't been released to the supermarket

### ISSUE THREAD

**Issue by cdelacruzpinto** [sous-chefs/apache2#463]
### Cookbook version
3.2.2

### Chef-client version
Chef: 12.17.44

### Platform Details
Ubuntu 16.04
### Scenario:

Recipe mod_php is not available in the last version of the apache2 cookbook released in the supermarket.
It is available, however, in the master branch, but it won't appear if I download the recipe from the supermarket. Because of this, I'm not able to submit P.R to fix other recipes including apache2::mod_php5 unconditionally. Please please please release another version of the cookbook with the contents of the master branch!

### Steps to Reproduce:
cd chef-repo
knife cookbook site download apache2
tar zxvf apache2-3.2.2.tar.gz
find |grep mod_php.rb

### Expected Result:
./recipes/mod_php.rb
./recipes/mod_php5.rb
./attributes/mod_php.rb
./attributes/mod_php5.rb

### Actual Result:
./attributes/mod_php5.rb
./recipes/mod_php5.rb

(The files mod_php.rb that would work in ubuntu 16.04 aren't available)

**Comment by ih16** [comment]
Any perspective on when this will be released?

**Comment by svanzoest** [comment]
@ih16 I have been working through integration tests and making sure we have everything in that we need. We should have a release out shortly.

**Comment by ih16** [comment]
@svanzoest Great! Thanks for the quick reply!

**Comment by DStape** [comment]
+1

**Comment by svanzoest** [comment]
Just pushed https://github.com/sous-chefs/apache2/releases/tag/v3.3.0

**Comment by DStape** [comment]
Thank you.
