### ISSUE TITLE
Apache2 service forces use of Debian provider on debian-like machines

### ISSUE THREAD

**Issue by sterago** [sous-chefs/apache2#467]
### Cookbook version
3.2.2

https://github.com/sous-chefs/apache2/blob/master/recipes/default.rb#L217

Is there a specific reason why the default provider cannot be used in this case?

**Comment by svanzoest** [comment]
This is because of #151 which was because of the Ubuntu switch from Upstart to Systemd, so we forced the Debian provider. That was a while ago, so it is probably worth while to test to see if this is still a necessity.

**Comment by damacus** [comment]
Closing due to a little lack of detail. 

If this still occurs on master, please don't hesitate to reopen  against the current version of master
