### ISSUE TITLE
Jessie php handlers are not configured

### ISSUE THREAD

**Issue by e100** [sous-chefs/apache2#479]
### Cookbook version
3.3.0
### Chef-client version
12.19.36
### Platform Details
Debian Jessie
### Scenario:
Get php working

### Steps to Reproduce:
include_recipe "apache2:mod_php"

### Expected Result:
Setup working mod_php 

### Actual Result:
A working php.conf is placed in mods-available/php.conf
This working config is NOT symlinked in mods-enabled resulting in a lack of php handlers

**Comment by svanzoest** [comment]
Hmm.. yeah, not sure why I set `conf false`.
https://github.com/sous-chefs/apache2/blob/master/recipes/mod_php.rb#L99

**Comment by eyespies** [comment]
This is also affecting CentOS / RHEL. I also noticed, as mentioned in #480 that the conf file is just 'php.conf' while the load file is 'php5.load'. I believe that a2enmod would normally create a symlink for both the conf and the load file, but they have to be named the same. So even if you add `conf true`, the config file will not be created properly.

**Comment by eyespies** [comment]
I think that the line https://github.com/sous-chefs/apache2/blob/master/attributes/mod_php.rb#L20 will also need updated to be just 'php'

**Comment by pwalz** [comment]
Like #480, I think this one has been resolved by #514.

**Comment by damacus** [comment]
Boom thanks @pwalz !
