### ISSUE TITLE
CentOS / RHEL v 6.x Tests Removed?

### ISSUE THREAD

**Issue by eyespies** [sous-chefs/apache2#481]
### Cookbook version
3.3.0

### Chef-client version
```
chef-client -v
Chef: 12.19.36
```

### Platform Details
CentOS 6.9

### Scenario:
I was working on a fix for #480 / #479 and checked the unit / integration tests. I noticed that in 3.3.0, all the test config files in `test/integration/default/inspec/localhost/platforms/` for CentOS and RHEL 6.x have been removed. Was there a reason for removing support for these OS platforms which are still in production support? Also, I would have expected support to be dropped in a major version bump (e.g. 3 -> 4), not in a minor version bump (e.g. 3.2 -> 3.3). If this was not intentional, I can copy the test configs from a previous release and finish my work.

### Steps to Reproduce:
Try to fix #480 and #479 for CentOS 6.x and run the tests.

### Expected Result:
I should be able to run the tests.

### Actual Result:
I can't run the tests for a previously supported OS.

**Comment by svanzoest** [comment]
We don't actively test on rhel 6.X any longer, however, it should still work. The test matrix is quite large, so we primarily focus on the latest major versions.

**Comment by eyespies** [comment]
Does the apache2 cookbook follow semantic versioning? I would have expected removal of OS support to result in a major version bump since it technically is a breaking change by removing guaranteed backwards compatibility.

**Comment by svanzoest** [comment]
We did not remove OS support, just the tests. The changes made to support PHP7 which passed in the tests is what is the issue here. The module is loaded, however, the config was not loaded which got missed in the tests.

**Comment by eyespies** [comment]
I agree that you haven't really removed OS support, just the tests.

That said, my fear would be that if the tests are removed, someone could introduce code that is backwards incompatible with an older OS. And without tests, we cannot confirm that new code is indeed backwards compatible with an old release.

So while the code technically still supports the older OS, without tests, we cannot be certain of that fact and from the perspective of someone who relies on the code to work and support our autoscale environment, without tests for our OS platform, we cannot rely on the newest versions of the cookbook. 

With semantic versioning (so specific OS support, nor tests ensuring that support, are removed in minor releases) + full test coverage, an end user can be more confident that going from 3.2 to 3.3 won't break a system and possibly cause an outage.

Hopefully that perspective makes sense. For the moment, it seems we'll have to stick with 3.2.2 of this cookbook (which, by the way, we do appreciate your maintaining) which has the tests for our OS platform. Once we upgrade to CentOS 7, we can move to 3.3.0 and later.

**Comment by svanzoest** [comment]
I get what you are saying and I would love to run tests on every platform we have support for it is that it would take a few days to run. So unfortunately we limit it to the latest release only. Otherwise there are just too many manage.

I think if 3.2.2 works for you, then sticking to that is an excellent plan for rhel 6.

**Comment by koertkuipers** [comment]
so yeah. they did really drop support for rhel 6
