### ISSUE TITLE
File /etc/sysconfig/httpd24 is generated instead of /etc/sysconfig/httpd

### ISSUE THREAD

**Issue by klarakarl** [sous-chefs/apache2#486]
When cookbook is configured to install httpd24 package wrong config file is generated

### Cookbook version
    v3.3.0 (2017-04-11)
### Chef-client version
   12.17.44

### Platform Details
    Amazon Linux AMI release 2016.09 (should be reproduced on any RHEL)

### Scenario:
Set apache environment variables via 
  node['apache']['sysconfig_additional_params']
using the following set also
  node['apache']['package']='httpd24'

### Steps to Reproduce:
Should be reproduced on any RHEL based system. 
Was observed on Amazon Linux AMI release 2016.09
set 
   node['apache']['package']='httpd24'
set
   node['apache']['sysconfig_additional_params']={"foo"=>"bar"}

### Expected Result:
File updated with environment variables for apache 
   /etc/sysconfig/httpd

### Actual Result:
Instead the cookbook works and generates -  /etc/sysconfig/httpd24
This file is not applied by the /etc/init.d/httpd startup script.
The script uses  - /etc/sysconfig/httpd24
=======
Notice: 
The  /etc/init.d/httpd startup script is written that way so if you create a link
   /etc/init.d/httpd24 ->  /etc/init.d/httpd
and start apache with
  /etc/init.d/httpd24 start

/etc/sysconfig/httpd24 will get applied. So unless  node['apache']['package']='httpd24' this bug is not reproduced.

**Comment by klarakarl** [comment]
Pull request - https://github.com/sous-chefs/apache2/pull/488

**Comment by tas50** [comment]
Fixed on master. Thanks
