### ISSUE TITLE
Version control missing

### ISSUE THREAD

**Issue by gorazdzagar** [sous-chefs/apache2#498]
### Cookbook version
5.0.0

### Scenario:
Fixate the version to be installed

### Expected Result:
Expected to have **version** included with the package resource and default['apache']['version'] be present. 

### Actual Result:
Not possible to fixate the version which is a requirement to prevent automatic updates to newer releases.

**Comment by svanzoest** [comment]
`apache.version` was only used as a flag to determine if the cookbook should behave in `2.4` or in the default 2.2 mode.

The cookbook has no knowledge as to what version of the apache2 package is available when calling `package` and it is generally recommended to handle this at the package repository level.

**Comment by damacus** [comment]
Closing this down now as we're refactoring the cookbook heavily. 

If we decide to introduce package locking or something similar it'll be clearly marked as such.
