### ISSUE TITLE
Feature add mod_jk compilation for CentOS

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [sous-chefs/apache2#502]
Like `mod_auth_openid`, `mod_jk` requires compilation on some platforms and actually doesn't work.

**Comment by damacus** [comment]
Hey @shanethehat thanks for notifying us of this. 

Fancy submitting a PR for this functionality?

**Comment by SharpEdgeMarshall** [comment]
@damacus maybe you were talking to me?
I could make a PR basing the recipe on `mod_auth_openid` but i need help with needed packages.

**Comment by damacus** [comment]
Indeed! 

Give us a shout in the sous-chefs slack if you need a hand.

**Comment by svanzoest** [comment]
My personal opinion has been to remove all non-standard httpd modules outside of this cookbook and handle them separately. E.g. if the source does not live at https://github.com/apache/httpd/tree/trunk/modules and is not a standard module provided at http://httpd.apache.org/ then it should be moved into it's own separate cookbook.

This includes things like `mod_pagespeed`, `mod_auth_openid`, `mod_jk`, etc.

**Comment by SharpEdgeMarshall** [comment]
@svanzoest Too late, i just made PR :joy: 
If mod_jk should be in his own cookbook let me now so i could move code there.

**Comment by cheeseplus** [comment]
+1 for this not being part of the core cookbook as it's not a standard module

**Comment by josephholsten** [comment]
Can we document the goal of removing those modules in the readme? I'm sure someone else will make a similar request in future.

**Comment by damacus** [comment]
Closing this as stale issue. If someone wants to take up documenting why/what/how please re-open or just fix. 

Thanks!
Dan
