### ISSUE TITLE
Request ability to set apache2.conf Mutex mode

### ISSUE THREAD

**Issue by Meh-Lindi** [sous-chefs/apache2#512]
### Chef-client version
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2

### Platform Details
Debian

### Scenario:
I need to edit the apache2.conf "global" setting Mutex to set which mode of mutex I am using.
For my (apache, fcgid php) Debian it is recommended to have Mutex sem default, not Mutex file:[spethomg]
This is not related to the mod_ssl mutex

### Expected Result:
apache2.conf global setting of 
`Mutex sem default`

**Comment by svanzoest** [comment]
You can drop in a template in conf-enabled using the definitions to
override or append anything in the global apache configuration.

**Comment by Meh-Lindi** [comment]
Yes I have done that now.
I was just surprised that you could set the Mutex file directory with a node setting, but not actually the mode.
Thanks.
