### ISSUE TITLE
How to install the specfic version of the apache using this cookbook as ther is no attribute defined in the cookbook to provide the version details

### ISSUE THREAD

**Issue by samakode** [sous-chefs/apache2#517]
### Cookbook version
5.0.1

### Chef-client version
12.19.36

### Platform Details
Cent os 7.1 rhel family.  Azure cloud

### Scenario:
Trying to install the fixed version of apache 2.4.17

### Steps to Reproduce:
How to specify a specific version of apache

### Expected Result:
Fix the version of apache to 2.4.17 even if the new version is available via node attribute. 

### Actual Result:
After running this cookbook apache is upgraded to latest version automatically and overwrite the f8xed version that i am trying to install.

**Comment by damacus** [comment]
Hi there!

we've recently done a sizable refactor, but would be happy to receive a PR to make the tunable. 

Thanks,
Dan

**Comment by josephholsten** [comment]
generally we like to solve this at the package-management level: configure a yum repo and pin the package number. We would definitely love some documentation explaining this pattern, but it's somewhat outside the scope of this cookbook.
