### ISSUE TITLE
Discussion, dropping support for apache 2.2

### ISSUE THREAD

**Issue by damacus** [sous-chefs/apache2#522]
Should we drop support for apache 2.2 in favour of the up to date, patched (from a module perspective) 2.4?

**Comment by gsreynolds** [comment]
My two cents from a maintainability POV, yes absolutely. However, my understanding was that this was done in [v5.0.0](https://github.com/sous-chefs/apache2/blob/master/CHANGELOG.md#v500-2017-07-13)? 

For the discussion it might be useful to summarise what needs to be done on top of what was done in 5.0.0 for those not familar?

Related: https://github.com/afklm/jira/issues/107, https://github.com/parallels-cookbooks/confluence/issues/161

**Comment by damacus** [comment]
We might need a removes-2.2 support set of items or whatever then. 

There's a tonne of things in the code base that can be simplified if we remove 2.2.
