### ISSUE TITLE
ports.conf empty with latest chef-client (13.7.16)

### ISSUE THREAD

**Issue by mawatech** [sous-chefs/apache2#523]
### Cookbook version
5.0.1

### Chef-client version
13.7.16

### Platform Details
CentOS 7

### Scenario:
Just run the apache2 default recipe

### Steps to Reproduce:
Just run the apache2 default recipe. A small example deployment will be attached.

### Expected Result:
Apache installed.

### Actual Result:
 ```
           ================================================================================
           Error executing action `start` on resource 'service[apache2]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl --system start httpd ----
           STDOUT: 
           STDERR: Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.
           ---- End output of /bin/systemctl --system start httpd ----
           Ran /bin/systemctl --system start httpd returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb
           
           199: service 'apache2' do
           200:   service_name apache_service_name
           201:   supports [:start, :restart, :reload, :status]
           202:   action [:enable, :start]
           203:   only_if "#{node['apache']['binary']} -t", environment: { 'APACHE_LOG_DIR' => node['apache']['log_dir'] }, timeout: 10
           204: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:199:in `from_file'
           
           service("apache2") do
             action [:enable, :start]
             updated true
             default_guard_interpreter :default
             service_name "httpd"
             enabled true
             running false
             masked false
             pattern "apache2"
             declared_type :service
             cookbook_name "apache2"
             recipe_name "default"
             supports {:start=>true, :restart=>true, :reload=>true, :status=>true}
             only_if "/usr/sbin/httpd -t"
           end
           
           System Info:
           ------------
           chef_version=13.7.16
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-client worker: ppid=4682;start=09:38:00;
           executable=/opt/chef/bin/chef-client

```
Problem seems to be an empty ports.conf:

```
[vagrant@default-centos-7 ~]$ sudo cat /etc/httpd/ports.conf 
# This file was generated by Chef for default-centos-7.vagrantup.com.
# Do NOT modify this file by hand!

[vagrant@default-centos-7 ~]$ 
```
This breaks between chef 13.6.26 and 13.6.27.

So if you set `chef_omnibus_install_options: -v 13.6.26 -c current` in the .kitchen.yml it works.

```
[vagrant@default-centos-7 ~]$ sudo cat /etc/httpd/ports.conf 
# This file was generated by Chef for default-centos-7.vagrantup.com.
# Do NOT modify this file by hand!

Listen *:80
[vagrant@default-centos-7 ~]$ 
```

So some of these commits break the deployment: https://github.com/chef/chef/compare/v13.6.26...v13.6.27

Also the latest current version (14.0.24 while writing this issue) is broken.

**Comment by mawatech** [comment]
[apache2_chef_failure.zip](https://github.com/sous-chefs/apache2/files/1659330/apache2_chef_failure.zip)

Just unzip, run `berks install` and then `kitchen verify -l debug default-centos-7`

**Comment by rcambien** [comment]
I have the same problem and after some investigations, the only recipe that update the ports.conf file is mod_ssl ... if you don't include the mod_ssl recipe, the ports.conf file is left blank.

**Comment by damacus** [comment]
Hey all!

thanks for reporting this issue, would you mind trying the same using the master branch? 

It's 'bleeding edge right now, with pg_gem not working right now. But most other features should work out of the box including this one.

**Comment by mawatech** [comment]
master branch is also broken.

**Comment by mawatech** [comment]
I added logging to https://github.com/sous-chefs/apache2/blob/master/libraries/listen.rb 

```
    def merge_listen_attributes(node)
      retval = (Apache2::Listen.converted_listen_ports_and_addresses(node) + node['apache']['listen']).uniq
      Chef::Log.fatal('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
      Chef::Log.fatal("RETVAL is #{retval}")
      Chef::Log.fatal('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
      retval
    end
```

which outputs `[2018-01-24T12:03:41+00:00] FATAL: RETVAL is []`

After adding another logging to https://github.com/sous-chefs/apache2/blob/master/recipes/default.rb at line 173

```
ruby_block 'lognode' do
  block do
    Chef::Log.fatal('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
    Chef::Log.fatal("node['apache']['listen'] is #{node['apache']['listen']}")
    Chef::Log.fatal('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
  end
end
```
and running the deployment again it is working

`[2018-01-24T12:06:22+00:00] FATAL: RETVAL is ["*:80"]`

I have no clue why :confused:

**Comment by Dispader** [comment]
Hey @mawatech — I'm seeing exactly the error you're seeing, here— and started to just after Chef Client 13.7.16 released.  Does your above message indicate that you're not getting the error anymore?

**Comment by Dispader** [comment]
@rcambien I think the problem is a bit deeper than that: I am including `mod_ssl`, and I'm still getting the error.

If it helps anyone here, manually setting `['apache']['listen']` seems to be a temporary workaround.

```Ruby
# WORKAROUND, https://github.com/sous-chefs/apache2/issues/523
node.default['apache']['listen'] = ['*:80', '*:443']
```

**Comment by Dispader** [comment]
Just a heads-up for folks: while the above issue seems to take care of the port opening issue, there appear to be deeper problems (here, SSL, permissions, VHost configuration).  I'm suspecting the Chef Client version update recently, but I'm going to verify this.

**Comment by Dispader** [comment]
Small update: reverting the Chef Client to `13.6.4` does make this particular problem go away.  (I've specified it in the metadata for the cookbook on which I've been testing, and in `.kitchen.yml` for the tests.)

(Personal note: I'm having other problems, even after this reversion, but they may be specific to what I'm doing.  Reverting Chef Client seems to open ports in the way that folks were accustomed to.)

**Comment by mawatech** [comment]
I think that this one is the root cause:

https://github.com/chef/chef/issues/6784

**Comment by marzdgzmn** [comment]
> # WORKAROUND, https://github.com/sous-chefs/apache2/issues/523
> node.default['apache']['listen'] = ['*:80', '*:443']

Tried the workaround, but it is not working.

**Comment by Dispader** [comment]
@damacus I haven't tried this against `master`, but I did run the tests that caused `httpd` restart failures against [v5.2.1](https://github.com/sous-chefs/apache2/releases/tag/v5.2.1), and the [workaround](https://github.com/sous-chefs/apache2/issues/523#issuecomment-362534117) is still required for my particular wrapper Cookbook.
