### ISSUE TITLE
Error executing action `restart` on resource 'service[apache2]'

### ISSUE THREAD

**Issue by ramdasj** [sous-chefs/apache2#524]
Chef Development Kit Version: 2.4.17
chef-client version: 13.7.16
platform rhel- 7.4 and 7.0

### Scenario:
using apache2 as a dependency in my cookbook where i need the apache2 to be installed.

### Steps to Reproduce:
while converging using kitchen this error popped up

* service[apache2] action restart

           ================================================================================
           Error executing action `restart` on resource 'service[apache2]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /bin/systemctl --system restart httpd ----
           STDOUT:
           STDERR: Job for httpd.service failed. See 'systemctl status httpd.service' and 'journalctl -xn' for details.
           ---- End output of /bin/systemctl --system restart httpd ----
           Ran /bin/systemctl --system restart httpd returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb

           206: service 'apache2' do
           207:   service_name apache_service_name
           208:   case node['platform_family']
           209:   when 'rhel'
           210:     if node['platform_version'].to_f < 7.0
           211:       restart_command "/sbin/service #{apache_service_name} restart && sleep 1"
           212:       reload_command "/sbin/service #{apache_service_name} graceful && sleep 1"
           213:     end
           214:   when 'debian'

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:206:in `from_file'

           service("apache2") do
             action [:enable, :start]
             updated true
             default_guard_interpreter :default
             service_name "httpd"
             enabled true
             running false
             masked false
             pattern "apache2"
             declared_type :service
             cookbook_name "apache2"
             recipe_name "default"
             supports {:start=>true, :restart=>true, :reload=>true, :status=>true}
             only_if "/usr/sbin/httpd -t"
           end

           System Info:
           ------------
           chef_version=13.7.16
           platform=redhat
           platform_version=7.0
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
           program_name=chef-solo worker: ppid=1188;start=18:02:52;
           executable=/opt/chef/bin/chef-solo

         * service[apache2] action reload (up to date)

       Running handlers:
       [2018-01-25T18:04:07-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-01-25T18:04:07-05:00] ERROR: Exception handlers complete
       Chef Client failed. 91 resources updated in 01 minutes 15 seconds
       [2018-01-25T18:04:07-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-01-25T18:04:07-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-01-25T18:04:07-05:00] ERROR: Chef::Exceptions::MultipleFailures
       [2018-01-25T18:04:07-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
D      Cleaning up local sandbox in /var/folders/1b/dftr8v2512g9f9hcgv113s9w0000gn/T/default-RHEL-74-sandbox-20180125-24420-sgtrrd

----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --no-color --json-attributes /tmp/kitchen/dna.json  --force-formatter
']

**Comment by ramdasj** [comment]
@martinisoft please help me with this issue in cookbook, i have apache installed but it doesn't restart

**Comment by ramdasj** [comment]
@tas50 please guide on this

**Comment by svanzoest** [comment]
Can you provide the output from systemd that gives the specific error?
> STDERR: Job for httpd.service failed. See 'systemctl status httpd.service' and 'journalctl -xn' for details.

`systemctl status httpd.service` and `journalctl -xn` should provide more insight as to why the restart is failing.

**Comment by damacus** [comment]
Hi there!

would you mind trying to replicate this failure on the current master branch of the cookbook?
From what I've seen this is no longer an issue, but if it is please reopen

Thanks,
Dan
