### ISSUE TITLE
32-bit ARM is flagged as a 64-bit architecture

### ISSUE THREAD

**Issue by don-code** [sous-chefs/apache2#529]
### Cookbook version
5.0.1

### Chef-client version
13.8.5

### Platform Details
CentOS 7 on 32-bit ARM

### Scenario:
Running the `default` recipe.

### Steps to Reproduce:
The minimal Chef run list `recipe[apache2]` when bootstrapped against a 32-bit ARM machine is sufficient to reproduce.

### Expected Result:
Apache httpd should install and start up.

### Actual Result:
Apache httpd installs but cannot start, because `/etc/httpd/modules` is erroneously linked to `/usr/lib64/httpd/modules`. It should be linked to `/usr/lib/httpd/modules`, as this is a 32-bit architecture.

**Comment by damacus** [comment]
Closed via #530
