### ISSUE TITLE
fast_cgi

### ISSUE THREAD

**Issue by nuheluxulu** [sous-chefs/apache2#563]
### Cookbook version
5.2.1

### Chef-client version
14.5.33

### Platform Details
CentOS Linux release 7.5.1804 - Cloudinit image http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1809.qcow2

### Scenario:
Trying to get fast_cgi to work with the cookbook

### Steps to Reproduce:
Made a wrapper cookbook with the only difference:
default['apache']['default_modules'] += %w(proxy fcgid)

### Expected Result:
That apache starts and that fast cgi works.
I believe we can use mod_fcgid.x86_64 instead of the http://superb-east.dl.sourceforge.net/sourceforge/mod-fcgid/mod_fcgid.2.2.tgz in recipe/mod_fgcid.rb

### Actual Result:
When trying to start apache:
httpd: Syntax error on line 112 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mods-enabled/fcgid.load: Cannot load /usr/lib64/httpd/modules/mod_fcgid.so into server: /usr/lib64/httpd/modules/mod_fcgid.so: undefined symbol: ap_unixd_setup_child

**Comment by mengesb** [comment]
I would think what you want is `node.default['apache']['default_modules'] << %w(proxy fcgid)` ...

`+=` is commonly string concatenation, `<<` is commonly array appending

**Comment by damacus** [comment]
This will change with the upcoming cookbook release once we have a direct module resource.

The guide will be, you can either pass in a new complete list to override the default modules list, or add another module to be installed via the `apache_module` resource. 
Watch this space 👍

**Comment by damacus** [comment]
Hi there!

would you mind trying to replicate this failure on the current master branch of the cookbook?
From what I've seen this is no longer an issue, but if it is please reopen

Thanks,
Dan
