### ISSUE TITLE
Amazon-2 and Fedora support

### ISSUE THREAD

**Issue by damacus** [sous-chefs/apache2#597]
# Brief Description 🗣 

The delayed restart action when apache2 is installed for the first time hangs due to some systemd bug. This doesn't seem to happen on most platforms 🤔 

## Cookbook version 👩‍🍳 

v6.0

## Chef-client version 👨‍🍳 

Latest

## Platform Details 🚆 

- Amazon linux 2
- Fedora 28+

## Scenario 📖 

Install apache2 on amazon linux or a new Fedora.

## Steps to Reproduce 🌀 

Install apache2 cookbook v6.0 on Amazon Linux 2

## Expected Result 👮 

The restart doesn't hang

**Comment by hugotongal** [comment]
Having the same issue with Amazon Linux 2

**Comment by htplbc** [comment]
Having the same issue on Amazon Linux 2

**Comment by danbuchal** [comment]
@damacus and @htplbc can you confirm what the latest versions are in these repos?  I believe this could be the same issue as mentioned here: https://github.com/sous-chefs/apache2/issues/636#issuecomment-499527579

**Comment by danbuchal** [comment]
I want to make sure @benclark 's comment doesn't get lost:
https://github.com/sous-chefs/apache2/issues/636#issuecomment-518768014

His suggestion of enabling extended_status did resolve the issue for me:

```
apache2_install 'default' do
  mpm 'event'
  mod_conf(
    status: {
      extended_status: 'On'
    }
  )
end
```
