### ISSUE TITLE
mod_proxy is failing due to missing default value for :require property

### ISSUE THREAD

**Issue by bottkv488** [sous-chefs/apache2#598]
# Brief Description

CR mod_proxy is setting an emtpy string as value for the :require property.
Leaving the `Require` directive empty causes apache to fail.

I suggest keeping the behaviour of apache2 <= 6.0.0 where the defaults were set to `all denied`:
https://github.com/sous-chefs/apache2/blob/de761545bc80809d384ba33ed61542d43fe16a4d/attributes/default.rb#L254

## Cookbook version

6.0.0

## Chef-client version

13.x, 14.x

## Platform Details

all platforms

## Scenario

using mod_proxy

**Comment by bottkv488** [comment]
PR is on the way

**Comment by damacus** [comment]
Looks like we need a test for this! If you can figure out what we need to write in the unit and integration tests. We'll happily merge away :)

**Comment by damacus** [comment]
As a note, the fix has now been merged in, but we should have a test for this.

**Comment by bottkv488** [comment]
I added a context in my latest PR which at least covers the valid creation of the conf file:
https://github.com/sous-chefs/apache2/pull/604/files

As for behavioral/inspec tests:
there seem to be quite a lot of tasks involved (creating fixtures for mod setup, creating inspec test coverage for core modules)? 😧

**Comment by damacus** [comment]
Fixed by #601
