### ISSUE TITLE
deprecate(d) :docroot_dir property in apache2_config?

### ISSUE THREAD

**Issue by bottkv488** [sous-chefs/apache2#606]
# Brief Description
the `docroot_dir` property is not used by `templates/apache2.conf.erb`.

I guess this was the plan (see https://github.com/sous-chefs/apache2/blob/de761545bc80809d384ba33ed61542d43fe16a4d/templates/default/apache2.conf.erb#L71)

We might want to reduce obfuscation here?

## Additional Thoughts
The `default_docroot_dir` helper method can still be useful for wrapper cookbooks.

On centos httpd ships with 

```shell
Main DocumentRoot: "/etc/httpd/htdocs"
```
whereas the helper would spit out `'/var/www/html'` which would cause access denied errors in all vhost configs where `DocumentRoot` is not explicitly defined.

## Cookbook version

v6.0.0

## PR
@damacus I wait for your opinions/approval before filing a PR?

**Comment by damacus** [comment]
Fixed as part of #611. As we're now using this. Thanks for spotting this!
