### ISSUE TITLE
Function precedence issue with `default_log_dir` in filebeat cookbook

### ISSUE THREAD

**Issue by brodygov** [sous-chefs/apache2#609]
# Brief Description

The `default_log_dir` helper in the apache2 cookbook version 6.0.0 overrides the same helper function in the filebeat cookbook, which has a different method signature.

https://github.com/vkhatri/chef-filebeat/blob/87343911b6aa6e034c8ac979f670ba8b089fdb12/libraries/helper.rb#L69-L71

```ruby
    def default_log_dir(conf_dir)
```

vs

https://github.com/sous-chefs/apache2/blob/2fcb45ec68d3769b824530f21dfb613390a8e1ce/libraries/helpers.rb#L148-L157

https://github.com/sous-chefs/apache2/issues/605 appears to be another issue with the same underlying cause of the apache2 cookbook injecting its helpers globally.

Are these includes necessary?

https://github.com/sous-chefs/apache2/blob/2fcb45ec68d3769b824530f21dfb613390a8e1ce/libraries/helpers.rb#L432-L433

## Cookbook version

6.0.0

## Chef-client version

13.10.4

## Platform Details

Ubuntu 16.04

## Scenario

Use the apache2 and filebeat cookbooks in the same run list.

## Actual Result

```
         * filebeat_install[default] action create
           
           ================================================================================
           Error executing action `create` on resource 'filebeat_install[default]'
           ================================================================================
           
           ArgumentError
           -------------
           wrong number of arguments (given 1, expected 0)
           
           Cookbook Trace:
           ---------------
           /var/lib/kitchen/cache/cookbooks/apache2/libraries/helpers.rb:148:in `default_log_dir'
           /var/lib/kitchen/cache/cookbooks/filebeat/resources/install.rb:29:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /var/lib/kitchen/cache/cookbooks/identity-elk/recipes/filebeat.rb
           
            28: filebeat_install 'default' do
            29:   version '6.4.2'
            30: end
            31: 
           
           Compiled Resource:
           ------------------
           # Declared in /var/lib/kitchen/cache/cookbooks/identity-elk/recipes/filebeat.rb:28:in `from_file'
           
           filebeat_install("default") do
             action [:create]
             default_guard_interpreter :default
             declared_type :filebeat_install
             cookbook_name "identity-elk"
             recipe_name "filebeat"
             version "6.4.2"
             conf_dir "/etc/filebeat"
             prospectors_dir "/etc/filebeat/conf.d"
           end
           
           System Info:
           ------------
           chef_version=13.10.4
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
           program_name=chef-client worker: ppid=30116;start=23:42:34;
           executable=/opt/chef/bin/chef-client
```

**Comment by damacus** [comment]
Hey! 

Thanks for submitting this issue. 

These can go away as soon as we drop recipe support.

I think the best thing to do here is release another major version, and drop all recipes. This should allow some upgrade path from the recipe way. All be it with this bug included.

**Comment by bottkv488** [comment]
Hi,
I just commited https://github.com/sous-chefs/apache2/pull/610 which addresses a similar issue

**Comment by damacus** [comment]
This should be fixed by #611. Please comment and reopen if this isn't the case

**Comment by KindAchmed** [comment]
Hey,
i experienced the same error on version 7.1.0.
But its slightly different from what @brodygov error.
Do you want me to open another issue?

`================================================================================
           Error executing action `enable` on resource 'apache2_default_site[bxx]'
           ================================================================================

           ArgumentError
           -------------
           wrong number of arguments (given 0, expected 1)

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/filebeat/libraries/helper.rb:66:in `default_log_dir'
           /tmp/kitchen/cache/cookbooks/apache2/resources/default_site.rb:56:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/apache2/resources/default_site.rb:44:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/sxxxxxx-bxx/recipes/apache.rb

            80:   apache2_default_site 'bxx' do
            81:     default_site_name 'bxx'
            82:     template_source 'host.conf.erb'
            83:     action :enable
            84:   end
            85: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/sxxxxxx-bxx/recipes/apache.rb:80:in `from_file'

           apache2_default_site("bxx") do
             action [:enable]
             default_guard_interpreter :default
             declared_type :apache2_default_site
             cookbook_name "sxxxxxx-bxx"
             recipe_name "apache"
             default_site_name "bxx"
             template_source "host.conf.erb"
             apache_root_group "root"
             log_dir "/var/log/httpd"
           end

           System Info:
           ------------
           chef_version=14.11.21
           platform=centos
           platform_version=7.5.1804
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
           program_name=/opt/chef/bin/chef-solo
           executable=/opt/chef/bin/chef-solo

         * ruby_block[purge_prospectors_dir] action run (skipped due to only_if)

       Running handlers:
       [2019-06-03T10:26:21+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2019-06-03T10:26:21+00:00] ERROR: Exception handlers complete
       Chef Client failed. 12 resources updated in 21 seconds
       [2019-06-03T10:26:21+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2019-06-03T10:26:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2019-06-03T10:26:21+00:00] FATAL: ArgumentError: apache2_default_site[bxx] (sxxxxxx-bxx::apache line 80) had an error: ArgumentError: wrong number of arguments (given 0, expected 1)`

**Comment by damacus** [comment]
Hi @KindAchmed if you could open a new issue that would be great. 


Thanks,
Dan
