### ISSUE TITLE
Override package installed

### ISSUE THREAD

**Issue by niallfleming** [sous-chefs/apache2#614]
# Brief Description

Is it no longer possible to override the package name in the Apache2 cookbook?

## Cookbook version

7.0.0

## Chef-client version

12 & 14

## Platform Details

CentOS7

## Scenario

I wish to install a later version of Apache 2.4 via the httpd24u package from IUS repo. But there doesn't seem to be a way to install a specific package instead of the cookbook defined package. Not using the apache2_install resource would achieve this aim, but then presumably I don't get the advantage of the cookbook managing the apache config?

## Steps to Reproduce

apache2_install 'default'

## Expected Result

httpd24u to be installed instead of httpd

## Actual Result

httpd installed

**Comment by damacus** [comment]
I've been pondering the right way to do this request. We can totally allow an override of the package resource. 

What I'm more interested about is the UIS repo. I've not heard of this before. How widely used is it and do you think we could bake the repo install into this cookbook?

**Comment by niallfleming** [comment]
IUS is a rackspace supported CentOS package repo. - https://ius.io/

I think it's reasonably well respected.

You could bake it in, there's an rpm to install the repo, but equally the repo paths never change so could bake those into the cookbook.

**Comment by niallfleming** [comment]
Any ETA on this change? I see you merged IUS support into HAProxy!

 I don't have time this week to make a fork to try and handle this myself, but maybe next week, if you haven't managed it by then.

**Comment by damacus** [comment]
If you could throw a fix in I'd love it, I'm busy trying to make the website less ugly this week :)
