### ISSUE TITLE
Apache Server child pid 637 exit signal Segmentation fault (11), possible coredump in /etc/apache2 Issue

### ISSUE THREAD

**Issue by rigalpatel001** [sous-chefs/apache2#627]
# Brief Description
I am facing apache server issue. I have check apache server logs and seems likes its go in infinate loop. error log continuously display below errors.

```
[Tue Apr 30 09:46:59.387053 2019] [core:notice] [pid 11409] AH00051: child pid 20380 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Apr 30 09:46:59.387261 2019] [core:error] [pid 11409] AH00546: no record of generation 0 of exiting child 20380
[Tue Apr 30 09:46:59.387326 2019] [core:notice] [pid 11409] AH00051: child pid 20381 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Apr 30 09:46:59.387391 2019] [core:error] [pid 11409] AH00546: no record of generation 0 of exiting child 20381
[Tue Apr 30 09:46:59.387453 2019] [core:notice] [pid 11409] AH00051: child pid 20382 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Apr 30 09:46:59.387531 2019] [core:error] [pid 11409] AH00546: no record of generation 0 of exiting child 20382
[Tue Apr 30 09:46:59.387592 2019] [core:notice] [pid 11409] AH00051: child pid 20383 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Tue Apr 30 09:46:59.387646 2019] [core:error] [pid 11409] AH00546: no record of generation 0 of exiting child 20383

```
## Platform Details

**PHP**        7.2.15
**0ubuntu** 0.18.10.2
**Server version:** Apache/2.4.34 (Ubuntu)
**Server built:**   2019-04-03T12:50:09

When I restart apache server Site is working.

Anyone please suggest solution to fix this issue?

Thanks

**Comment by Xorima** [comment]
To troubleshoot this we will need more information, Can we get the recipe you are using to configure apache2 and the steps which you are using to reproduce this behaviour?

**Comment by rigalpatel001** [comment]
Hello,

i have used below link steps to configure apache server.

https://www.linode.com/docs/web-servers/lamp/install-lamp-stack-on-ubuntu-18-04/

Thanks

**Comment by Xorima** [comment]
Are you using chef to configure the server or following the guide manually?

**Comment by rigalpatel001** [comment]
Nope, I have configure server manually using guide.

**Comment by damacus** [comment]
Hi @rigalpatel001 we only support the chef cookbook installed version of apache2
