### ISSUE TITLE
Unable to install latest Apache version on CentOS 7 using CodeIT repo.

### ISSUE THREAD

**Issue by danbuchal** [sous-chefs/apache2#636]
# Brief Description

Unable to install latest version of Apache via CodeIT Repo.

## Cookbook version

7.0.0

## Chef-client version

15.0.300

## Platform Details

CentOS Linux release 7.5.1804

## Scenario

CentOS 7's default repo only contains Apache 2.4.6
I am adding the [CodeIT Repo](https://codeit.guru/en_US/) in order to install the latest version of Apache for HTTP2 support. 
See: https://crosp.net/blog/administration/install-latest-apache-server-centos-7/

## Steps to Reproduce

Prior to calling apache2_install add the CodeIT repo:

```
# Add Yum Repo for CodeIT (Required for latest Apache/HTTP2)
yum_repository 'codeit' do
  baseurl "https://repo.codeit.guru/packages/centos/#{node['platform_version'].to_i}/$basearch"
  gpgkey 'https://repo.codeit.guru/RPM-GPG-KEY-codeit'
end
```

## Expected Result

Latest version of Apache is installed (2.4.39)

## Actual Result

Installation of 2.4.39 begins, but hangs attempting to *reload* service (restart works).
This reload eventually fails after 900 seconds.

Status of service shows:
```
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: reloading (reload) since Wed 2019-05-22 19:13:08 UTC; 1min 40s ago
     Docs: man:httpd.service(8)
  Process: 15444 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
 Main PID: 15168 (httpd)
   Status: "Reading configuration..."
   CGroup: /system.slice/httpd.service
           ├─15168 /usr/sbin/httpd -DFOREGROUND
           ├─15445 /usr/sbin/httpd -DFOREGROUND
           ├─15512 /usr/sbin/httpd -DFOREGROUND
           └─15513 /usr/sbin/httpd -DFOREGROUND
```

**Comment by danbuchal** [comment]
After some trial and error, I don't think the "hangs" during reload are due to the OS or the repo being used. I think it has to do with the version of Apache being installed.

I made some manual modifications to the cookbook to allow me to install different versions. 
After some trial and error, I discovered that installing version `2.4.27` **works**, while installing `2.4.28` breaks with the above-mentioned behavior.

**Comment by damacus** [comment]
@danbuchal thanks for the investigation on this one. Are there more up to date repos we can use to install Apache2?

**Comment by danbuchal** [comment]
Hi @damacus, the repo I'm using is up to date.  To confirm, I also tried the IUS repo which also has the same issue.  The latest Apache version is 2.4.39.  The problem is that this cookbook fails with the mentioned "hang" during restart for any version after 2.4.27 (I tried them all).
The answer lies somewhere in *what* chaneged from 2.4.27 -> 2.4.28.  I have had to shift my attention, so I don't know what exactly the breaking change is.

**Comment by benclark** [comment]
I'm not sure how helpful this will be, but I wanted to share my "fix" - I was experiencing the same problem on Amazon-2 (came here from #597), and I found this thread:

https://github.com/iusrepo/httpd24u/issues/23#issuecomment-421001228

In my case, I was pretty consistently seeing an issue with `reload` only when mod_status was turned on. Enabling `ExtendedStatus` actually fixed this for me. I'm not wild about the solution, since it's not something I actually need or want enabled, but it got me unblocked for now.

**Comment by damacus** [comment]
Sorry I missed this under an avalanche of notifications!

Adding mod status to the default modules works for me, especially if it unblocks most of the newer platform should.

**Comment by damacus** [comment]
Moving this conversation over to #597
