### ISSUE TITLE
Recipe compilation error in Debian 9

### ISSUE THREAD

**Issue by nilroy** [sous-chefs/apache2#637]
# Brief Description

I am not using this cookbook directly but I am using rundeck cookbook which is dependent on 7.0.0 version of this cookbook. We are using chef-solo to provision the instances. When I start provisioning the rundeck I see below error:

```
================================================================================
Recipe Compile Error in /etc/chef/local-mode-cache/cache/cookbooks/apache2/resources/conf.rb
================================================================================

ArgumentError
-------------
Validation map has unknown check: description

Cookbook Trace:
---------------
  /etc/chef/local-mode-cache/cache/cookbooks/apache2/resources/conf.rb:11:in `class_from_file'

Relevant File Content:
----------------------
/etc/chef/local-mode-cache/cache/cookbooks/apache2/resources/conf.rb:

  4:           default: lazy { "#{apache_dir}/conf-available" },
  5:           description: 'Path to the conf-available directory'
  6:
  7:  property :root_group, String,
  8:           default: lazy { default_apache_root_group },
  9:           description: ''
 10:
 11>> property :template_cookbook, String,
 12:           default: 'apache2',
 13:           description: 'Cookbook to source the template from. Override this to provide your own template'
 14:
 15:  property :options, Hash,
 16:           default: {
 17:             server_tokens: 'Prod',
 18:             server_signature: 'On',
 19:             trace_enable: 'Off',
 20:           },

System Info:
------------
chef_version=13.8.5
platform=debian
platform_version=9.4
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-solo worker: ppid=19548;start=07:45:20;
executable=/opt/chef/bin/chef-solo
```

## Cookbook version
7.0.0 (Same thing happens with 7.0.2 )

## Chef-client version

chef_version=13.8.5

## Platform Details

debian 9.4

## Scenario

[What you are trying to achieve and you can't?]

## Steps to Reproduce

I tried Kitchen also. The same error is happening in the kitchen tests. Probably if you just try to run the rundeck cookbook creating some run list you should be able to see this.

## Expected Result

The chef-solo run will fail in the compilation phase

## Actual Result

Error details in the description

**Comment by ccrebolder** [comment]
This cookbook requires a minimum chef-client version of 13.9, which is when the property descriptions were added: https://github.com/sous-chefs/apache2/pull/624

I think the minimum version as specified in the metadata for 7.0.X was incorrect, but it is correct in 7.1.0.

**Comment by nilroy** [comment]
@ccrebolder so I need to upgrade chef in order to make it work

**Comment by ccrebolder** [comment]
Unfortunately yes. Chef client 13 went end-of-life on April 30th so I expect more of these problems will arise in the next few months. https://docs.chef.io/versions.html#end-of-life-eol-products

**Comment by nilroy** [comment]
@ccrebolder thanks for the support.
