### ISSUE TITLE
mod_php does not get installed in version 7.1.0

### ISSUE THREAD

**Issue by lordkage** [sous-chefs/apache2#638]
# Brief Description

`apache2_module 'php'` does not install/verify prerequisite php is installed, and therefore, silently causes an issue.

## Cookbook version

`7.1.0`

## Chef-client version

```
Chef: 14.13.11
```

## Platform Details

`Centos 7`

## Scenario

Following the "basic usage" guide from the README, but adding `apache2_module 'php'` to install mod_php as well. The wrapper recipe is applied, but when chef-client goes to restart, it fails because the mod_php.so is not found. Subsequent converges appear to be working, but they are because there are no changes, so the service is still borked.

## Steps to Reproduce

1. Create a wrapper recipe as described on README
2. Add `apache2_module 'php'` as resource to be applied
3. Converge

## Expected Result

`mod_php` and dependancies to be installed like in versions <= 6.0.0, which will allow apache2 to start/restart on first converge.

## Actual Result

`mod_php` and dependancies are not installed. Resulting in apache2 being unable to start/restart.
```
Jun 15 18:37:34 localhost httpd: httpd: Syntax error on line 80 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mods-enabled/php.load: Cannot load /usr/lib64/httpd/modules/mod_php.so into server: /usr/lib64/httpd/modules/mod_php.so: cannot open shared object file: No such file or directory
```

**Comment by lordkage** [comment]
For the immediate fix, I added the following to my recipe to fix it:
```
package 'php'
apache2_module 'php5' do
  mod_name 'libphp5.so'
end
```

It also looks like this is a carry over from issue #576, which means this might be reporting of a known issue.

**Comment by JohnRoesler** [comment]
Yes - it looks like a known issue by @damacus. Prior to the conversion to custom resources - there was a recipe for mod_php https://github.com/sous-chefs/apache2/blob/de761545bc80809d384ba33ed61542d43fe16a4d/recipes/mod_php.rb which looks like it indeed installed `package 'php'`

I propose we close this issue and track to the original #576 - perhaps give that issue a comment to remind folks it still needs doing 👍

**Comment by lordkage** [comment]
Done.
