### ISSUE TITLE
Inconsistent naming of cookbook / template_cookbook parameter

### ISSUE THREAD

**Issue by madwort** [sous-chefs/apache2#644]
# Brief Description

`resources/default_site` uses `cookbook` to mean the same thing as `resources/conf` does for `template_cookbook`. They should be the same.

## Cookbook version

7.1.0

## Scenario

When developing a wrapper cookbook around this cookbook, I expect parameters to have consistent names across the cookbook.

**Comment by damacus** [comment]
Likewise,please feel free to drop prs into fix these inconsistencies.
