### ISSUE TITLE
template_cookbook param documented but not implemented for apache2_module

### ISSUE THREAD

**Issue by madwort** [sous-chefs/apache2#645]
# Brief Description

`template_cookbook` is documented for apache2_module but doesn't appear to be implemented. 

## Cookbook version

7.1.0

## Scenario

When developing a wrapper cookbook that uses this cookbook, I expect the documentation to correspond to the implemented features.

**Comment by damacus** [comment]
I haven't seen anyone use it yet so removing the documentation sounds like the best idea

**Comment by leinster** [comment]
I've just run into this. I'd like to see this implemented as a feature but this might just be misunderstanding how to use the cookbook. I'd like to get rid of the `/icons` alias set up by default in the `mods/alias.conf.erb` template - is there another way to do this that doesn't involve overriding the template?

Also w/r/t the same doc page:
- the examples use a `filename` property that isn't mentioned in the properties list
- the examples use `action`, again unmentioned in the properties list - I guess this is implicit?
- the doc say "see the recipes directory" which doesn't seem to exist

Thanks for the cookbook!
