### ISSUE TITLE
Array.to_sym does not work

### ISSUE THREAD

**Issue by mrmarbury** [sous-chefs/apache2#647]
## :ghost: (Not so) Brief Description

In the helper library the function `default_modules()` returns an Array of module names. Later each element is converted :to_sym. That won't work for:

libraries/helpers.rb (lines: 269-271)
```ruby
     when 'arch', 'freebsd'
        default_modules << %w(log_config logio unixd)
     when 'suse'
        default_modules << %w(log_config logio)
```
This will lead to an Array within an Array. To make this work the final variable should be either flattened or the Arrays should be concatenated with `:concat`

## :pancakes: Cookbook version

7.1.1

## :woman_cook:  Chef-Infra Version

Client: 15.1

## :tophat: Platform details

FreeBSD 12

## Steps To Reproduce

Do this for FreeBSD (and the SuSE part on SuSE)

```ruby
apache2_install 'default_install'
```
## :police_car: Expected behavior

... installs all default modules

**Comment by damacus** [comment]
I'm 99.999% sure this is a freebsd Ruby problem 🤔

Any suggestion on how we can fix this bug 🐛 I'm all ears!

**Comment by mrmarbury** [comment]
Hmm, pretty sure it is not. Let me show you in IRB on macos 

```ruby
2.5.1 :001 > %w(a b c d) << %w(d e f)
 => ["a", "b", "c", "d", ["d", "e", "f"]]
2.5.1 :002 > %w(a b c d).concat(%w(d e f))
 => ["a", "b", "c", "d", "d", "e", "f"]
```
I'd probably use :concat. If you want do remove duplicates then do a :uniq afterwards

Cheers

**Comment by damacus** [comment]
Sounds like you have a good test for this, want to make a PR for this issue?

**Comment by mrmarbury** [comment]
I will create one. Hopefully I find the time before I head out on a vacation for 2 weeks

**Comment by zmaupin** [comment]
Fixed here https://github.com/sous-chefs/apache2/commit/ff9465fb8c68a7a06d94ece6cab3660ce32d0544#diff-38a4aeddb4e620724d3b85362cb8b939
