### ISSUE TITLE
Can some one help me to build .deb file from apache sorce using debuild. I wish to learn it from scrap. I admit that Iam a noob in this field, can someone help me, it will be very helpful.

### ISSUE THREAD

**Issue by unni-krishnan-95** [sous-chefs/apache2#672]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by JohnRoesler** [comment]
I would recommend reaching out in the chef community somewhere and see if you can find some assistance https://community.chef.io/
