### ISSUE TITLE
apache2_config and web_app resource equivalent in current version?

### ISSUE THREAD

**Issue by YogiKhan** [sous-chefs/apache2#679]
**Cookbook version**
8.0.1
**Chef-client version**
Latest
**Platform Details**
All supported platforms
**Scenario:**
apache2_config and web_app resource equivalent in current version?
We were using 

`apache_config 'mod_status' do
      enable false
end

web_app node['apache']['virtual_host_name']`

We upgraded the chef client version but now it fails for both.
`Unsupported database type! - Use a supported type or handle DB creation/config in a wrapper cookbook!
================================================================================
Recipe Compile Error in /tmp/cookbooks/xxxx/config/local-mode-cache/cache/cookbooks/xxxx/recipes/default.rb
================================================================================
NoMethodError
# Cookbook Name:: xxxxx
-------------
undefined method `enable' for Custom resource apache_config from cookbook apache2`

**Comment by damacus** [comment]
Closing as this doesn't use the standard template.
