### ISSUE TITLE
PIDFILE is not rendered in /etc/sysconfig/httpd

### ISSUE THREAD

**Issue by limitusus** [sous-chefs/apache2#720]
## :ghost: Brief Description

Template variable `apache_pid_file` is not passed from the `install` resource.
https://github.com/sous-chefs/apache2/blob/v8.5.0/templates/etc-sysconfig-httpd.erb#L31
always renders like:

```
PIDFILE=
```

`install` resource does not pass `apache_pid_file` template variable to the template.
https://github.com/sous-chefs/apache2/blob/v8.5.0/resources/install.rb#L242-L246

## :pancakes: Cookbook version

8.5.0

## :woman_cook:  Chef-Infra Version

All

## :tophat: Platform details

`platform_family?('rhel', 'amazon', 'fedora', 'suse')`

In my case, AmazonLinux 1 affected.
`/etc/init.d/httpd start` could not set a correct PID file path as `PIDFILE` is empty, and failed to execute `daemon` helper function.

## Steps To Reproduce

Render `/etc/sysconfig/httpd` with `install resource`

## :police_car: Expected behavior

`apache_pid_file` (from helpers) should be filled in the template.

## :heavy_plus_sign: Additional context

N/A

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. Please don't hesitate to ask if you need help or guidance on submitting! 

If you need help or wish to discuss the issue, please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by damacus** [comment]
This is now being fixed as part of #802
