### ISSUE TITLE
ServerName directive absent from apache2.conf.erb

### ISSUE THREAD

**Issue by karthanistyr** [sous-chefs/apache2#728]
## :ghost: Brief Description

The `config` resource allows for setting the ServerName directive in apache2.conf, as per
https://github.com/sous-chefs/apache2/blob/2a48478d115ba9f156cb10eb0bae0b79fec1d0ec/resources/config.rb#L54-L56

But the default template in `templates/default/apache.conf.erb` does not have a ServerName directive, nor a placeholder for the template variable.

Also telling, the `install` resource does not expose `server_name`, so there's an inconsistency here.

## :pancakes: Cookbook version

HEAD; also using v8.7.0 in my cookbook.

## :woman_cook:  Chef-Infra Version

N/A

## :tophat: Platform details

N/A

## Steps To Reproduce

```ruby
apache2_config 'apache2.conf' do
  server_name 'some_server_name'
end
```
## :police_car: Expected behavior

The ServerName directive would be settable via the resource.

## :heavy_plus_sign: Additional context

N/A

**Comment by karthanistyr** [comment]
> Also telling, the install resource does not expose server_name, so there's an inconsistency here.

Actually, it *is* supported, but is not documented.

**Comment by ramereth** [comment]
@karthanistyr do you mind making a PR which adds some supporting documentation?
