### ISSUE TITLE
problem with apache2 

### ISSUE THREAD

**Issue by SATadsl** [sous-chefs/apache2#732]
Hello 

I'm trying to install Graphite on my Debian 10 machine 

but I have a problem with Apache2 

here is the problem 

Feb 11 11:37:17 Graphite apachectl[5921]: The Apache error log may have more information.
Feb 11 11:37:17 Graphite systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
Feb 11 11:37:17 Graphite systemd[1]: Reload failed for The Apache HTTP Server.
Feb 11 11:40:02 Graphite systemd[1]: Reloading The Apache HTTP Server.
Feb 11 11:40:02 Graphite apachectl[6015]: AH00526: Syntax error on line 3 of /etc/apache2/sites-enabled/apache2-graphite.conf:
Feb 11 11:40:02 Graphite apachectl[6015]: Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration
Feb 11 11:40:02 Graphite apachectl[6015]: Action 'graceful' failed.
Feb 11 11:40:02 Graphite apachectl[6015]: The Apache error log may have more information.
Feb 11 11:40:02 Graphite systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
Feb 11 11:40:02 Graphite systemd[1]: Reload failed for The Apache HTTP Server.

Please I really need your help

**Comment by ramereth** [comment]
@SATadsl can you please provide more detail on how this is happening? Can you provide some example code which replicates the problem? Also please include the version of Chef Infra Client and the cookbook.

Thanks!

**Comment by damacus** [comment]
Closing this issue as this doesn't look like a problem with the Chef cookbook we provide, but the apache2 program. Support for Apache2 can be found [here](https://httpd.apache.org/support.html).
