### ISSUE TITLE
Option to config using different instance name

### ISSUE THREAD

**Issue by ragsarag** [sous-chefs/apache2#758]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## 🙍🏼 Problem Statement

At moment i am using httpd cookbook, which is obsolete now, in that i have option to use instance name and configure httpd with different names eg:  httpd-default.service  and httpd-kibana.service

I am planning to use apache2 instead of httpd, but i could not find option to use instance name. 

## :grey_question: Possible Solution

provide option for user to specify instance name, like its available in httpd cookbook.

**Comment by damacus** [comment]
We don't currently support running multiple instances. And don't plan to as this makes configuration unnecessarily complicated.
