### ISSUE TITLE
apache2_module breaks authz_svn module loading

### ISSUE THREAD

**Issue by chuhn** [sous-chefs/apache2#760]
Hi y'all

Loading of the subversion Apache modules requires a strict load order:
1. `mod_dav`
2. `mod_dav_svn`
3. `mod_authz_svn`

At least on Debian Buster `apache2_module 'authz_svn'` breaks this load order by changing  `/etc/apache2/mods-available/authz_svn.load` from
```
# Depends: dav_svn
<IfModule !mod_dav_svn.c>
    Include mods-enabled/dav_svn.load
</IfModule>
LoadModule authz_svn_module /usr/lib/apache2/modules/mod_authz_svn.so
```
to
```
LoadModule authz_svn_module /usr/lib/apache2/modules/mod_authz_svn.so
```

The load files will then be included in alphabetic order and `apachectl configtest` complains about:
```
apache2:
  Syntax error on line 146 of /etc/apache2/apache2.conf:
    Syntax error on line 1 of /etc/apache2/mods-enabled/authz_svn.load:
      Cannot load /usr/lib/apache2/modules/mod_authz_svn.so into server:
         /usr/lib/apache2/modules/mod_authz_svn.so: undefined symbol:
           dav_svn_get_repos_path2
```

What would be the best way to circumvent this issue?
The contents of the `.load` file is thoroughly hard-coded in the `apache2_module` custom resource it seems …

Cheers

Christopher

**Comment by damacus** [comment]
@chuhn do you have code I can use to reproduce this? This sounds like something we should definitely look into.

**Comment by chuhn** [comment]
:+1:
