### ISSUE TITLE
apache_mod_php_filename and apache_mod_php_modulename incompatible with Ubuntu 22.04

### ISSUE THREAD

**Issue by Entreiu** [sous-chefs/apache2#764]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Ubuntu 22.04 has moved on from PHP 7 to PHP 8 and these resources do not reflect this update, particularly in that the correct apache2 modules are now called php8.1.load and php8.1.conf

## :pancakes: Cookbook version

Version 8.14.4

## :woman_cook:  Chef-Infra Version

17.7.29

## :tophat: Platform details

Ubuntu 22.04 LTS

## Steps To Reproduce

Use this cookbook to install apache2 and the apache2_mod_php resource.

## :police_car: Expected behavior

Installation of mod_php and activation of the correct php8.1.conf and php8.1.load files being linked into /etc/apache2/mods-enabled

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. Please don't hesitate to ask if you need help or guidance on submitting! 

If you need help or wish to discuss the issue, please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by damacus** [comment]
I'm going to close this issue and recommend anyone using mod_php move to php-fpm as it supports HTTP/2 which afaik, mod_php is never going to.
